Update 111

diff --git a/111 b/111
--- a/111
+++ b/111
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+# Function to validate IP address
+validate_ip() {
+    local ip=$1
+    if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+        return 0
+    else
+        return 1
+    fi
+}
+
 # Download necessary files
 wget https://github.com/penumbra-zone/penumbra/releases/download/v0.69.1/pd-x86_64-unknown-linux-gnu.tar.xz
 wget https://github.com/penumbra-zone/penumbra/releases/download/v0.69.1/pcli-x86_64-unknown-linux-gnu.tar.xz
@@ -19,14 +29,13 @@ sudo mv pd-x86_64-unknown-linux-gnu/pd /usr/bin
 rm CHANGELOG.md cometbft_0.37.2_linux_amd64.tar.gz LICENSE pcli-x86_64-unknown-linux-gnu.tar.xz pd-x86_64-unknown-linux-gnu.tar.xz README.md SECURITY.md UPGRADING.md
 rm -rf pcli-x86_64-unknown-linux-gnu pd-x86_64-unknown-linux-gnu
 
-# Prompt the user for IP address and validate input
-while true; do
+# Prompt the user for IP address
+read -p "Enter the IP address: " ip_address
+
+# Validate the entered IP address
+while ! validate_ip "$ip_address"; do
+    echo "Invalid IP address format. Please enter a valid IP address."
     read -p "Enter the IP address: " ip_address
-    if [[ $ip_address =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-        break
-    else
-        echo "Invalid IP address format. Please enter a valid IP address."
-    fi
 done
 
 # Prompt the user for moniker
@@ -54,6 +63,7 @@ WantedBy=multi-user.target" > /etc/systemd/system/pd.service
 printf "[Unit]
 Description=cometbft node
 After=network-online.target
+Requires=pd.service
 
 [Service]
 User=root
